name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change if your branch is named differently

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Updated to v4 for Node.js 20 support

      - name: Setup Node.js
        uses: actions/setup-node@v4  # Updated to v4 for Node.js 20 support
        with:
          node-version: 20  # Ensuring it uses the latest version
          cache: 'pnpm'  # Caching dependencies for faster builds

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Build Project
        run: pnpm build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4  # Updated to v4 for Node.js 20 support
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out  # Adjust if needed (e.g., `.next` folder for Next.js)
