name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust this if your default branch is different

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.1  # Align with the Node version you need
          cache: 'npm'  # Cache npm dependencies automatically

      - name: Install Dependencies
        run: npm install  # Install dependencies using npm

      - name: Build Project
        run: npm run build  # Build your project

      - name: Cache npm Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm  # Cache npm directory
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out  # Adjust based on your build output folder
